#!/usr/bin/with-contenv sh

# Setup transmission directories in already-mounted /zims dir
# This simplifies configuration
echo "Creating /config, /downloads, and /watch for transmission"
mkdir -p /config
mkdir -p /downloads/complete
mkdir -p /downloads/incomplete
mkdir -p /watch

chown -R abc:abc /watch /config /downloads
